version: '3.1'
services:
  postgres-db:
    image: postgres:15
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo18@2024
      - POSTGRES_DB=postgres
    restart: always
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo:
    image: odoo:17
    user: root
    depends_on:
      - postgres-db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo18@2024
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - ./web-data:/var/lib/odoo  
    restart: always
