lzc-sdk-version: "0.1"
name: Odoo
package: cloud.lazycat.app.odoo
version: 0.0.1
description: 一站式全业务链管理平台
homepage: ""
author: odoo
application:
  subdomain: odoo
  background_task: false
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://odoo.cloud.lazycat.app.odoo.lzcapp:8069/
services:
  postgres-db:
    image: registry.lazycat.cloud/mxuexxmy/library/postgres:8cce992e23d242ff
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo@2024
      - POSTGRES_DB=postgres
    binds:
      - /lzcapp/var/postgresql:/var/lib/postgresql/data/
  odoo:
    image: registry.lazycat.cloud/mxuexxmy/library/odoo:4322dc0dd371c438
    environment:
      - HOST=postgres-db
      - USER=odoo
      - PASSWORD=odoo@2024
    depends_on:
      - postgres-db
    binds:
      - /lzcapp/var/addons:/mnt/extra-addons
      - /lzcapp/var/etc:/etc/odoo
      - /lzcapp/var/web:/var/lib/odoo
