lzc-sdk-version: "0.1"
name: Odoo
package: cloud.lazycat.app.odoo
version: 0.0.2
description: 一站式全业务链管理平台
homepage: ""
author: odoo
application:
  subdomain: odoo
  background_task: false
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://odoo.cloud.lazycat.app.odoo.lzcapp:8069/
services:
  postgres:
    image: registry.lazycat.cloud/mxuexxmy/library/postgres:8967b07c4959a05e
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo18@2024
      - POSTGRES_DB=postgres
    binds:
      - /lzcapp/var/data:/var/lib/postgresql/data
  odoo:
    image: registry.lazycat.cloud/mxuexxmy/library/odoo:a498cae86713a721
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo18@2024
    depends_on:
      - postgres
    binds:
      - /lzcapp/var/extra-addons:/mnt/extra-addons
      - /lzcapp/var/odoo:/etc/odoo
