lzc-sdk-version: "0.1"
name: Odoo
package: cloud.lazycat.app.odoo
version: 0.0.1
description: 一站式全业务链管理平台
homepage: ""
author: odoo
application:
  subdomain: odoo
  background_task: false
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://odoo.cloud.lazycat.app.odoo.lzcapp:8069/
services:
  postgresql:
    image: registry.lazycat.cloud/mxuexxmy/bitnami/postgresql:3a05612e696be9d9
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_odoo
      - POSTGRESQL_DATABASE=bitnami_odoo
    binds:
      - /lzcapp/var/postgresql:/bitnami/postgresql
  odoo:
    image: registry.lazycat.cloud/mxuexxmy/bitnami/odoo:a23be3bbb0cd14b9
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - ODOO_DATABASE_HOST=postgresql
      - ODOO_DATABASE_PORT_NUMBER=5432
      - ODOO_DATABASE_USER=bn_odoo
      - ODOO_DATABASE_NAME=bitnami_odoo
    depends_on:
      - postgresql
    binds:
      - /lzcapp/var/odoo:/bitnami/odoo
